# ---------------------------------------------------------
# Vagrantfile
# Purpose: Define and provision all 5 VMs for Vprofile project
# ---------------------------------------------------------

Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true   # Auto-manage /etc/hosts for connectivity
  
  # Database VM
  config.vm.define "db01" do |db01|
    db01.vm.box = "bandit145/centos_stream9_arm"         # OS image
    db01.vm.hostname = "db01"                            # Hostname inside VM
    db01.vm.network "private_network", ip: "192.168.56.25" # Private IP
    db01.vm.provision "shell", path: "mysql.sh"          # Run DB script
  end

  # Memcache VM
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "bandit145/centos_stream9_arm"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.24"
    mc01.vm.provision "shell", path: "memcache.sh"
  end

  # RabbitMQ VM
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "bandit145/centos_stream9_arm"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.23"
    rmq01.vm.provision "shell", path: "rabbitmq.sh"
  end

  # Application VM (Tomcat)
  config.vm.define "app01" do |app01|
    app01.vm.box = "bandit145/centos_stream9_arm"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.22"
    app01.vm.provision "shell", path: "tomcat.sh"
    app01.vm.provider "vmware_desktop" do |vb|
      vb.memory = "1024"   # Allocate 1GB RAM
    end
  end

  # Web Layer VM (Nginx reverse proxy)
  config.vm.define "web01" do |web01|
    web01.vm.box = "spox/ubuntu-arm"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.21"
    web01.vm.provision "shell", path: "nginx.sh"
  end
end
# Note: Use 'vagrant up --provider vmware_desktop' to launch VMs with VMware